### ISSUE TITLE
Automa-Thomas missing

### ISSUE THREAD

**Issue by t-lohse** [P6-Project/P6#13]
I think it is prudent that `automa-thomas` is implemented immediately!
Please do so
Thank you

**Comment by t-lohse** [comment]
@MJHC @alexsteffensen @lass5588 @mksm20 Could any of you look at this as soon as possible?

**Comment by Laursen79** [comment]
I suggest something like this:
![automa-thomas](https://user-images.githubusercontent.com/69715502/225303144-2f0d6f07-39b9-4824-92e3-658acb65c40b.png)
